---
- name: Destroy VM
  google.cloud.gcp_compute_instance:
    project: "{{ gcp_project }}"
    zone: "{{ gcp_zone }}"
    name: "{{ gcp_vm_name }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    state: absent
  delegate_to: localhost
